export enum ERoute {
  NoUsePlanDetailRoot = "/home/plan/audit",
  PlanSource = "/home/plan/audit/plan-source",
  OneStopMultiUse = "/home/plan/audit/one-stop-multi-use",
  MetricsImprovement = "/home/plan/audit/metrics-improvement",
  LoadStop = "/home/plan/audit/load-stop",
  WithElectricity = "/home/plan/audit/with-electricity",
  PowerCutHouseholds = "/home/plan/audit/power-cut-households",
  FrequentPowerCut = "/home/plan/audit/frequent-power-cut",
  RiskUsers = "/home/plan/audit/risk-users",
  ServicePlan = "/home/plan/audit/service-plan",
  ConstructionPic = "/home/plan/audit/construction-pic",
  HighRiskPlace = "/home/plan/audit/high-risk-place",
  OnSiteInfo = "/home/plan/audit/on-site-info",
  OnSitePic = "/home/plan/audit/on-site-pic",
  DateAndSource = "/home/plan/audit/date-and-source",
  Review = "/home/plan/audit/review",
  EquipmentAllocation = "/home/plan/audit/equipment-allocation",
  MaterialAllocation = "/home/plan/audit/material-allocation",
}
